ran black formatter, updated README, removed junkyard code
fastforwardlabs/video-classification pull request #16
Opened 2021-12-16 22:27 UTC by melaniebeck

This final PR takes care of a few straggling issues such as re-running the black formatter, adding CLDR licensing headers to new code files, and removing unused code (any code in an AMP should be working code; anything not working should be removed before publishing the AMP).

2021-12-17 02:48 UTC, ValdezBalderas reviewed
I had a couple of question.
It was also nice to look the code from the previous PR.

2021-12-17 02:48 UTC, ValdezBalderas commented on README.md
Nice

2021-12-17 02:48 UTC, ValdezBalderas commented on vidbench/arguments.py
> +    "--model_type", default="i3d", type=str, required=True,
Personally I prefer the style above (one line per argument), but I guess the formatter disagrees. 
What's your own preference? If you agree with me then I'd ask to revert it. If you agree with the formatter, I'll let the two of you win :)

2021-12-17 02:48 UTC, ValdezBalderas commented on scripts/config.txt
> +#--overwrite_cache                          # not implemented
This is not working code. Do you still want to keep it for future development?

2021-12-17 15:42 UTC, melaniebeck commented on vidbench/arguments.py
> +    "--model_type", default="i3d", type=str, required=True,
Usually Black uses multiple lines for arguments when the line is too long, otherwise it leaves it on one line. I don't really have a preference either way.

2021-12-17 15:43 UTC, melaniebeck commented on scripts/config.txt
> +#--overwrite_cache                          # not implemented
This isn't code at all. This is a config file that is required in order to run the evaluation script.

2022-01-04 21:54 UTC, ValdezBalderas commented on scripts/config.txt
> +#--overwrite_cache                          # not implemented
Ok. My question was more about whether leaving in the commented-out flags was deliberate. Generally speaking, removing functionality of yet-to-be-implemented features makes the repo cleaner

2022-01-04 22:59 UTC, ValdezBalderas requested changes
A question and some requests.

2022-01-04 22:59 UTC, ValdezBalderas commented on vidbench/data/process.py
> +        # print(f"Skipping video {video_path_no_dir}, too few frames: {num_frames}")
Not in this commit, but should we remove this commented out code?

2022-01-04 22:59 UTC, ValdezBalderas commented on vidbench/arguments.py
> +    "--model_type", default="i3d", type=str, required=True,
Ok in this case I'll request to revert to multiple lines.

2022-01-04 22:59 UTC, ValdezBalderas commented on vidbench/arguments.py
> +    "--results_dir", default=".", type=str, required=False,
Request to revert to multiple lines.

2022-01-04 22:59 UTC, ValdezBalderas commented on vidbench/arguments.py
> +    "--no_cuda", action="store_true", help="Whether not to use CUDA when available"
Request to change to multiple lines.

2022-01-05 15:46 UTC, ValdezBalderas requested changes
Request to use urllib3 v1.26.5

2022-01-05 15:46 UTC, ValdezBalderas commented on requirements.txt
> +-e .
Not in this commit, but I am seeing an alert  regarding the use of urllib3.
It seems that there is a suggestion to change 
urllib3==1.26.3
to
urllib3==1.26.5
See
https://github.com/fastforwardlabs/video-classification/security/dependabot/requirements.txt/urllib3/open

2022-01-05 17:03 UTC, melaniebeck commented on vidbench/arguments.py
> +    "--no_cuda", action="store_true", help="Whether not to use CUDA when available"
Dude. I"m not going to hand change these all. If you want to change them to multiple lines, please feel free.

2022-01-05 17:07 UTC, melaniebeck commented on requirements.txt
> +-e .
I'll take a look at this when I look at the install issue Andrew mentioned.

2022-01-05 17:12 UTC, melaniebeck commented on vidbench/data/process.py
> +        # print(f"Skipping video {video_path_no_dir}, too few frames: {num_frames}")
resolved.

2022-01-05 17:19 UTC, merged